### ISSUE TITLE
Не могат да се пишат нецели числа като Input

### ISSUE THREAD

**Issue by Neychok** [Neychok/finance-calculator#3]
Като напиша примерно "4.5" като лихва и излиза тази грешка. 
```
System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at FinanceCalculator.CreditCalculator.CalculateResult(Object sender, EventArgs e) in #####\Source\Repos\finance-calculator\FinanceCalculator\CreditCalculator.aspx.cs:line 59
```
Може би програмата очаква запетая вместо точка, но запетая не може да се пише в полето.

**Comment by Megas97** [comment]
Виж първия отговор: https://stackoverflow.com/questions/18868848/convert-string-to-double-input-string-was-not-in-a-correct-format

**Comment by Neychok** [comment]
Оправи го
